# если пишем логи в Google Sheets
[gsheets]
enabled = true
sheet_name = "MENUS_LOG"                # имя таблицы (или листа)
spreadsheet_id = "1_abcDEFxxx..."       # ID таблицы в Google Drive

# сервис-аккаунт
type = "service_account"
project_id = "..."
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "menu-bot@your-project.iam.gserviceaccount.com"
client_id = "..."
token_uri = "https://oauth2.googleapis.com/token"
